name: Debug postinstall script
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
jobs:
  setup:
    if: |
      ! (
        contains(github.event.pull_request.labels.*.name, 'invalid')
        || contains(github.event.pull_request.labels.*.name, 'skip ci')
      )
    runs-on: ubuntu-latest
    env:
      repo-dirname: repo
      fd-src-dirname: fd-sources
      artifact-name: debug-package@${{ github.event.number && format('pr-{0}', github.event.number) || github.sha }}
      archive-filename: debug-package.tar.zst
      tarball-name: foo.tgz
      fd-cmd-name: fd/{target}{ext}
    outputs:
      artifact-name: ${{ env.artifact-name }}
      archive-filename: ${{ env.archive-filename }}
      tarball-name: ${{ env.tarball-name }}
      fd-cmd-name: ${{ env.fd-cmd-name }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./${{ env.repo-dirname }}

      - name: Download fd
        uses: robinraju/release-downloader@v1.11
        with:
          repository: sharkdp/fd
          latest: true
          fileName: "*"
          out-file-path: ./${{ env.fd-src-dirname }}

      - name: Enable Corepack (Automatically setup a package manager for Node.js)
        shell: bash
        run: |
          if type yarn >/dev/null 2>&1; then
            echo '[command]npm uninstall --global yarn'
            npm uninstall --global yarn
          fi
          if type pnpm >/dev/null 2>&1; then
            echo '[command]npm uninstall --global pnpm'
            npm uninstall --global pnpm
          fi
          corepack enable
          corepack enable npm

          (
            cd '${{ env.repo-dirname }}' \
            && echo "pnpm-store-path=$(pnpm store path --silent)" >> "${GITHUB_ENV}"
          )

      - name: Cache pnpm
        if: env.pnpm-store-path
        uses: actions/cache@v3
        with:
          key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ env.pnpm-store-path }}

      - name: Setup debug package
        shell: bash
        run: |
          readonly root_path="$PWD"
          readonly repo_path="${root_path}"'/${{ env.repo-dirname }}'
          readonly debugger_package_path="${repo_path}"'/postinstall-debug-package'

          (
            cd "${repo_path}" && {
              pnpm install
              pnpm run build
            }
          )

          (
            cd "${debugger_package_path}" && {
              pnpm pack
              find . -type f -name '*.tgz' -print0 | xargs -0 -t -n 1 tar --list --verbose --file
              mv ./*.tgz "${root_path}/${{ env.tarball-name }}"
            }
          )

          cp -r "${repo_path}"'/.github' "${root_path}"
          cp "${debugger_package_path}/postinstall.js" "${root_path}"
          echo '{}' > "${root_path}/package.json"

          readonly fd_src_dirpath="${root_path}"'/${{ env.fd-src-dirname }}'
          find "${fd_src_dirpath}" -type f -name '*.tar.gz' -print0 \
            | xargs -0 -t -n 1 tar -x --gzip --verbose --directory "${fd_src_dirpath}" --file
          unzip "${fd_src_dirpath}/*.zip" -d "${fd_src_dirpath}"
          find "${fd_src_dirpath}" -type f \( -name 'fd' -executable -o -name 'fd.exe' \) -print0 | while read -r -d '' fd_src_filepath; do
            fd_target_platform="$(
              realpath --relative-to="${fd_src_dirpath}" "${fd_src_filepath}" \
                | perl -pe 's/^fd-v\d+(?:\.\d+)+-|\/.*//g'
            )"

            fd_filepath_dest='${{ env.fd-cmd-name }}'
            if [[ "${fd_src_filepath}" == *'.exe' ]]; then
              fd_filepath_dest="${fd_filepath_dest//'{ext}'/.exe}"
            else
              fd_filepath_dest="${fd_filepath_dest//'{ext}'/}"
            fi
            fd_filepath_dest="${root_path}/${fd_filepath_dest//'{target}'/${fd_target_platform}}"

            mkdir -p "$(dirname "${fd_filepath_dest}")"
            mv "${fd_src_filepath}" "${fd_filepath_dest}"
          done

          find . -mindepth 1 -maxdepth 1 -type d \( -name '${{ env.repo-dirname }}' -o -name '${{ env.fd-src-dirname }}' \) -prune -o -print0 \
            | xargs -0 -t tar -c --file './${{ env.archive-filename }}' --zstd --verbose
        # Note: Convert the debug package into a single archive file. This is for the following reasons:
        #       + Maintaining file permissions and case sensitive files
        #         see https://github.com/actions/upload-artifact/blob/v3.1.2/README.md#maintaining-file-permissions-and-case-sensitive-files
        #       + Reduce the number of API calls
        #         see https://github.com/actions/upload-artifact/blob/v3.1.2/README.md#too-many-uploads-resulting-in-429-responses

      - name: Upload debug package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.archive-filename }}
          retention-days:
            1
            # The resulting artifact of the build is intended to be used in the next job.
            # There is no need to store them for long periods of time.

  debug-postinstall-script:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        package-manager:
          # - npm@1.4.29  # Throws "Reference Error: primordials is not defined"
          # - npm@2.15.12 # Throws "peerinvalid The package ajv@6.12.6 does not satisfy its siblings' peerDependencies requirements!"
          # - npm@3.10.10 # Throws "cb.apply is not a function"
          # - npm@4.6.1   # Throws "cb.apply is not a function"
          # - npm@5.10.0  # Throws "cb.apply is not a function"
          - npm@6.14.18
          - npm@7.24.2
          - npm@8.19.4
          - npm@9.6.4
          - yarn@1.22.19
          - yarn@2.4.3
          - yarn@3.5.0
          - yarn@4.0.0-rc.42
          # - pnpm@1.43.1  # Throws "Internal Error: Cannot find module '.../bin/pnpm.js'"
          # - pnpm@2.25.7  # Throws "TypeError: cb.apply is not a function"
          # - pnpm@3.8.1   # Throws "EACCES: permission denied, mkdir '/usr/local/pnpm-global'"
          # - pnpm@4.14.4  # Throws "EACCES: permission denied, mkdir '/usr/local/pnpm-global'"
          # - pnpm@5.18.10 # Throws "EACCES: permission denied, mkdir '/usr/local/pnpm-global'"
          # - pnpm@6.35.1  # Throws "ELIFECYCLE  Command failed with exit code -4058. .../node_modules/foo postinstall: Failed"
          - pnpm@7.32.0
          - pnpm@8.2.0
          - bun@0.5.9
        pnp: [false, true]
        exclude:
          - package-manager: bun@0.5.9
            os: windows-latest
          - package-manager: npm@6.14.18
            pnp: true
          - package-manager: npm@7.24.2
            pnp: true
          - package-manager: npm@8.19.4
            pnp: true
          - package-manager: npm@9.6.4
            pnp: true
          - package-manager: bun@0.5.9
            pnp: true
          # Plug'n'Play cannot be enabled in Yarn v1 on Windows
          - package-manager: yarn@1.22.19
            os: windows-latest
            pnp: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download debug package
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.setup.outputs.artifact-name }}
          path: ~/debug-package-artifact

      - name: Restore debug package
        shell: bash
        run: tar -x --file ~/debug-package-artifact/'${{ needs.setup.outputs.archive-filename }}' --zstd --verbose

      - name: Install Bun
        if: startsWith(matrix.package-manager, 'bun@')
        shell: bash
        run: |
          npm install --global --force '${{ matrix.package-manager }}'
          if [[ '${{ runner.os }}' == 'Windows' ]]; then
            # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
            # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
            npm config get prefix >> "${GITHUB_PATH}"
          fi

      - name: Enable Corepack (Automatically setup a package manager for Node.js)
        if: |
          ! startsWith(matrix.package-manager, 'bun@')
        shell: bash
        run: |
          if type yarn >/dev/null 2>&1; then
            echo '[command]npm uninstall --global yarn'
            npm uninstall --global yarn
          fi
          if type pnpm >/dev/null 2>&1; then
            echo '[command]npm uninstall --global pnpm'
            npm uninstall --global pnpm
          fi
          corepack enable
          corepack enable npm
          < ./package.json jq '.packageManager = "${{ matrix.package-manager }}"' > ./package.json~new
          mv ./package.json~new ./package.json

      - name: Run install
        uses: actions/github-script@v6
        env:
          RUNNER_TEMP_DIR: ${{ runner.temp }}
          TARBALL_PATH: ./${{ needs.setup.outputs.tarball-name }}
          FD_CMD_FILENAME: ./${{ needs.setup.outputs.fd-cmd-name }}
        with:
          script: |
            const script = require('./.github/workflows/run-install.cjs');
            return await script({
              github,
              context,
              core,
              glob,
              io,
              exec,
              fetch,
              require,
              __original_require__,
              packageManager: '${{ matrix.package-manager }}',
              pnp: ${{ matrix.pnp }},
            });

  # Successfully complete this job when all jobs have been completed.
  # Only by checking this job, it is possible to determine if CI is complete or not.
  # So we can simplify our GitHub status check configuration.
  # see https://github.com/orgs/community/discussions/26822
  # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L482-L498
  complete:
    name: Complete Workflow
    needs: debug-postinstall-script
    if:
      always() && github.event.pull_request
      # This job is required only for Pull Requests.
      # It does not need to be run on other branches.
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
        # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
        if: |
          contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
          || contains(needs.*.result, 'skipped')
        run: exit 1
